Info page
SobyUmell/kartateka-client pull request #7
Opened 2024-09-14 15:19 UTC by tRy-HaRd-tgn

2024-09-14 18:44 UTC, Hubulbib requested changes

2024-09-14 18:44 UTC, Hubulbib commented on src/pages/info/index.js
> +      <Button span="Upgrade">buisiness</Button>
Опечатка

2024-09-14 18:44 UTC, Hubulbib commented on src/shared/ui/button/index.js
> +import React from "react";
Для чего нужен импорт React тут?

2024-09-14 18:44 UTC, Hubulbib commented on src/widgets/info-container/index.js
> +import React from "react";
Импорт React для чего?

2024-09-14 18:53 UTC, tRy-HaRd-tgn commented on src/shared/ui/button/index.js
> +import React from "react";
Я создаю компоненты с помощью снипетов, rfc создаёт пустой компонент и автоматически импортирует реакт, исправлю

2024-09-15 07:16 UTC, Hubulbib approved these changes
Отличная работа

2024-09-15 07:17 UTC, merged