Page teka
SobyUmell/kartateka-client pull request #8
Opened 2024-09-17 21:59 UTC by tRy-HaRd-tgn

2024-09-18 17:49 UTC, Hubulbib requested changes

2024-09-18 17:49 UTC, Hubulbib commented on src/shared/ui/teka-input/index.js
> +import { useEffect } from "react";
Методы из одной библиотеки можно скомпоновать, просто перечислив их.

2024-09-18 17:49 UTC, Hubulbib commented on src/shared/ui/teka-input/index.js
> +  const array = ["Что хочешь попробовать", "Какую кофейню ищите"];
Вынести эту массив-константу в сегмент **_model_** в файл search-placeholder-data.

2024-09-18 17:49 UTC, Hubulbib commented on src/widgets/teka-widget/index.js
> +export const TekaWidget = ({ h, ...props }) => {
замени название props-а **h** на **label**

2024-09-18 17:49 UTC, Hubulbib commented on src/widgets/teka-widget/index.js
сделай разделение на ui, model. Текущий код из index.js перенеси в ui.

2024-09-18 17:49 UTC, Hubulbib commented on src/widgets/teka-widget/index.js
> +  const settings = {
вынеси в сегмент model

2024-09-18 17:49 UTC, Hubulbib commented on src/widgets/teka-widget/index.js
> +        <div className={styles.div}>
сделай каждый этот `div `(элемент карусели) в отдельный компонент _shared_ **PostItem**.

2024-09-18 17:49 UTC, Hubulbib commented on src/widgets/teka-widget/index.js
> +    infinite: true,
сделать его конечным

2024-09-19 10:05 UTC, Hubulbib requested changes
Косметические правки

2024-09-19 10:05 UTC, Hubulbib commented on src/pages/teka/index.js
> +import { TekaWidget } from "../../widgets/teka-widget/ui";
импортировать можно только через OpenAPI файл

2024-09-19 10:05 UTC, Hubulbib commented on src/pages/profile/index.js
> +import React from "react";
использовать деструктуризацию:
`import {useState} from "react"`

2024-09-19 15:20 UTC, tRy-HaRd-tgn commented on src/pages/profile/index.js
> +import React from "react";
это страничка темы

2024-09-19 15:27 UTC, Hubulbib approved these changes
Отличная работа

2024-09-19 15:28 UTC, merged